spring.application.name=inventory-service

# server
server.port = 8082

# default servlet mapping
server.servlet.context-path=/inventory

# db
spring.datasource.url=jdbc:postgresql://localhost:5432/learning-inventory-db
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

